In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
import statsmodels.api as sm
import math
import numpy as np
import statistics

## Question 1

#### Part A

In [2]:
binary = pd.read_csv("BinaryData.csv")

In [3]:
binary.head()

x  y
0 -0.969221  0
1  0.095676  0
2  0.589349  0
3  1.109713  0
4  1.530880  0

In [4]:
log_regression = LogisticRegression()

In [5]:
x = binary['x'].values.reshape(-1, 1)

In [6]:
y = binary['y'].values.reshape(-1,1)

In [7]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [8]:
log_regression.fit(X_train,y_train)

C:\Users\54208\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression()

In [9]:
y_pred=log_regression.predict(X_test)

In [10]:
y_pred = y_pred.reshape(-1,1)

In [11]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.25      0.40         4
           1       0.79      1.00      0.88        11

    accuracy                           0.80        15
   macro avg       0.89      0.62      0.64        15
weighted avg       0.84      0.80      0.75        15



In [12]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

Accuracy:  0.8


In [13]:
print('B1 = ' + str(log_regression.coef_))
print('B0 = ' + str(log_regression.intercept_))

B1 = [[1.02439124]]
B0 = [-0.57587082]


#### Part C

In [14]:
cur_x = 1
rate = 0.01 # Learning rate
precision = 0.000001 
previous_step_size = 1 #
max_iters = 500 # maximum number of iterations
iters = 0 #iteration counter
cur_b0 = 0
cur_b1 = 0

In [15]:
def gradient_function_b0(b0,b1,x,y):
    return 1/(1+math.e ** (b0 + b1*x)) - y

def gradient_function_b1(b0,b1,x,y):
    return x/(1+math.e ** (b0 + b1*x))

In [16]:
while previous_step_size > precision and iters < max_iters:
    cur_y = 1/(1 + math.e ** -(cur_b0 + cur_b1 * cur_x))
    prev_b0 = cur_b0
    prev_b1 = cur_b1
    cur_b0 = cur_b0 - (rate * gradient_function_b0(prev_b0,prev_b1,cur_x,cur_y))
    cur_b1 = cur_b1 - (rate * gradient_function_b1(prev_b0,prev_b1,cur_x,cur_y))
    
    iters = iters+1 #iteration count
print("The minimum for b0 is ", cur_b0)
print("The minimum for b1 is ", cur_b1)

The minimum for b0 is  -3.604836015904874
The minimum for b1 is  -4.302418007952443


## Question 2

#### Part A

In [17]:
binary.head()

x  y
0 -0.969221  0
1  0.095676  0
2  0.589349  0
3  1.109713  0
4  1.530880  0

In [18]:
binary_y0 = binary[binary['y']==0]
binary_y1 = binary[binary['y']==1]

In [19]:
total_y = binary['y'].count()
pi_0 = binary_y0['y'].count() / total_y
pi_1 = binary_y1['y'].count() / total_y

In [20]:
average_x0 = binary_y0['x'].mean()
average_x1 = binary_y1['x'].mean()

In [21]:
binary_y0['var'] = binary_y0.apply(lambda x: (x['x'] - average_x0) ** 2, axis=1)
binary_y1['var'] = binary_y1.apply(lambda x: (x['x'] - average_x1) ** 2, axis=1)

<ipython-input-21-5ee0e48f288e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  binary_y0['var'] = binary_y0.apply(lambda x: (x['x'] - average_x0) ** 2, axis=1)
<ipython-input-21-5ee0e48f288e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  binary_y1['var'] = binary_y1.apply(lambda x: (x['x'] - average_x1) ** 2, axis=1)


In [22]:
var_x0 = binary_y0['var'].sum() / (binary_y0['x'].count() - 1)
var_x1 = binary_y1['var'].sum() / (binary_y1['x'].count() - 1)

In [23]:
print('pi0 : ' + str(pi_0))
print('mu0 : ' + str(average_x0))
print('var0: ' + str(var_x0))
print('\n')
print('pi1 : ' + str(pi_1))
print('mu1 : ' + str(average_x1))
print('var1: ' + str(var_x1))



pi0 : 0.3333333333333333
mu0 : -1.0408340855860843e-17
var0: 0.999999999947119


pi1 : 0.6666666666666666
mu1 : 2.99999999995
var1: 3.9999999998285545


#### Part B

In [24]:
def decision_boundary_y0(x):
    return -1/2 * math.log(var_x0) - 1/2 * (-x - average_x0) + math.log(pi_0)

In [25]:
def decision_boundary_y1(x):
    return -1/2 * math.log(var_x1) - 1/2 * (-x - average_x1) + math.log(pi_1)

In [26]:
print('decision_boundary_y0 : ' + str(decision_boundary_y0(3)))
print('decision_boundary_y1 : ' + str(decision_boundary_y1(3)))

decision_boundary_y0 : 0.40138771135833085
decision_boundary_y1 : 1.901387711328321


## Question 3

In [27]:
titanic = pd.read_csv('Titanic.csv')

In [28]:
titanic = titanic.drop('Name',axis=1)

#### Part A

In [29]:
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].mean())

In [30]:
titanic_y = titanic['Survived']
titanic_x = titanic.drop('Survived',axis=1)

In [31]:
part_C_titanic_x = pd.get_dummies(titanic_x, columns = ['Pclass','Sex','Embarked'])

#### Part B

In [32]:
titanic_X_train,titanic_X_test,titanic_y_train,titanic_y_test = train_test_split(part_C_titanic_x,titanic_y,test_size=141)

#### Part C

In [33]:
titanic_logit_model=sm.Logit(titanic_y_train,titanic_X_train)
titanic_result=titanic_logit_model.fit()

Optimization terminated successfully.
         Current function value: 0.435963
         Iterations 6


In [34]:
print(titanic_result.summary())

                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  750
Model:                          Logit   Df Residuals:                      740
Method:                           MLE   Df Model:                            9
Date:                Tue, 16 Feb 2021   Pseudo R-squ.:                  0.3454
Time:                        17:37:59   Log-Likelihood:                -326.97
converged:                       True   LL-Null:                       -499.49
Covariance Type:            nonrobust   LLR p-value:                 7.046e-69
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Age           -0.0397      0.009     -4.581      0.000      -0.057      -0.023
SibSp         -0.3570      0.123     -2.905      0.004      -0.598      -0.116
Parch         -0.1248      0.128     -0.975      0.3

In [35]:
titanic_y_pred = titanic_logit_model.predict(titanic_result.params,titanic_X_test)

In [36]:
titanic_y_pred = list(map(round, titanic_y_pred))

In [37]:
# confusion matrix 
cm = confusion_matrix(titanic_y_test, titanic_y_pred)  
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(titanic_y_test, titanic_y_pred))

Confusion Matrix : 
 [[76 11]
 [16 38]]
Test accuracy =  0.8085106382978723


In [38]:
titanic_lda = LinearDiscriminantAnalysis()
titanic_lda_model = titanic_lda.fit(titanic_X_train,titanic_y_train)

In [39]:
titanic_lda_y_pred = titanic_lda_model.predict(titanic_X_test)

In [40]:
print(confusion_matrix(titanic_lda_y_pred, titanic_y_test))
print(classification_report(titanic_y_test, titanic_lda_y_pred, digits=3))

[[75 17]
 [12 37]]
              precision    recall  f1-score   support

           0      0.815     0.862     0.838        87
           1      0.755     0.685     0.718        54

    accuracy                          0.794       141
   macro avg      0.785     0.774     0.778       141
weighted avg      0.792     0.794     0.792       141



In [41]:
titanic_qda = QuadraticDiscriminantAnalysis()
titanic_qda_model = titanic_qda.fit(titanic_X_train,titanic_y_train)
titanic_qda_y_pred = titanic_qda_model.predict(titanic_X_test)

C:\Users\54208\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [42]:
print(confusion_matrix(titanic_qda_y_pred, titanic_y_test))
print(classification_report(titanic_y_test, titanic_qda_y_pred, digits=3))

[[67 19]
 [20 35]]
              precision    recall  f1-score   support

           0      0.779     0.770     0.775        87
           1      0.636     0.648     0.642        54

    accuracy                          0.723       141
   macro avg      0.708     0.709     0.708       141
weighted avg      0.724     0.723     0.724       141



#### Part D

In [43]:
part_D_titanic_x = pd.get_dummies(titanic_x, columns = ['Sex','Embarked'])

In [44]:
titanic_X_train,titanic_X_test,titanic_y_train,titanic_y_test = train_test_split(part_D_titanic_x,titanic_y,test_size=141)

In [45]:
titanic_logit_model=sm.Logit(titanic_y_train,titanic_X_train)
titanic_result=titanic_logit_model.fit()
print(titanic_result.summary())

Optimization terminated successfully.
         Current function value: 0.442404
         Iterations 9
                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  750
Model:                          Logit   Df Residuals:                      741
Method:                           MLE   Df Model:                            8
Date:                Tue, 16 Feb 2021   Pseudo R-squ.:                  0.3376
Time:                        17:37:59   Log-Likelihood:                -331.80
converged:                       True   LL-Null:                       -500.88
Covariance Type:            nonrobust   LLR p-value:                 3.040e-68
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass        -1.1331      0.154     -7.343      0.000      -1.435      -0.831
Age           -0.0425      0.

C:\Users\54208\Anaconda3\lib\site-packages\statsmodels\base\model.py:1354: RuntimeWarning: invalid value encountered in sqrt
  bse_ = np.sqrt(np.diag(self.cov_params()))
C:\Users\54208\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1932: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


In [46]:
titanic_y_pred = titanic_logit_model.predict(titanic_result.params,titanic_X_test)
titanic_y_pred = list(map(round, titanic_y_pred))
# confusion matrix 
cm = confusion_matrix(titanic_y_test, titanic_y_pred)  
print ("Confusion Matrix : \n", cm)  
  
# accuracy score of the model 
print('Test accuracy = ', accuracy_score(titanic_y_test, titanic_y_pred))

Confusion Matrix : 
 [[78 12]
 [15 36]]
Test accuracy =  0.8085106382978723


In [47]:
titanic_lda = LinearDiscriminantAnalysis()
titanic_lda_model = titanic_lda.fit(titanic_X_train,titanic_y_train)
titanic_lda_y_pred = titanic_lda_model.predict(titanic_X_test)

print(confusion_matrix(titanic_lda_y_pred, titanic_y_test))
print(classification_report(titanic_y_test, titanic_lda_y_pred, digits=3))

[[78 15]
 [12 36]]
              precision    recall  f1-score   support

           0      0.839     0.867     0.852        90
           1      0.750     0.706     0.727        51

    accuracy                          0.809       141
   macro avg      0.794     0.786     0.790       141
weighted avg      0.807     0.809     0.807       141



In [48]:
titanic_qda = QuadraticDiscriminantAnalysis()
titanic_qda_model = titanic_qda.fit(titanic_X_train,titanic_y_train)
titanic_qda_y_pred = titanic_qda_model.predict(titanic_X_test)

print(confusion_matrix(titanic_qda_y_pred, titanic_y_test))
print(classification_report(titanic_y_test, titanic_qda_y_pred, digits=3))

[[69 10]
 [21 41]]
              precision    recall  f1-score   support

           0      0.873     0.767     0.817        90
           1      0.661     0.804     0.726        51

    accuracy                          0.780       141
   macro avg      0.767     0.785     0.771       141
weighted avg      0.797     0.780     0.784       141



C:\Users\54208\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


### Question 4

#### Part A

In [49]:
question4_x = [8.2344,4.4854, 5.4821, 1.0953, 2.1565, 2.5096, 4.9772,2.4998,4.2628,.6933]

In [50]:
q4_mean = (sum(question4_x)) / 10

In [51]:
sum_x_variance = 0
for x in question4_x:
    value = (x-q4_mean) ** 2
    sum_x_variance = sum_x_variance + value

q4_variance = sum_x_variance/9

In [52]:
q4_variance

5.258855416

In [53]:
q4_D = q4_variance/q4_mean

In [54]:
print(q4_D)

1.4448833994570889


#### Part B

In [55]:
np.random.seed(42)
randomly_generated_x = np.random.randint(0,10 , size=100)

In [56]:
print('random mean: ' + str(randomly_generated_x.mean()))
print('random var: ' + str(randomly_generated_x.std()/ (10 ** .5)))

random mean: 4.91
random var: 0.9034323438974277


In [57]:
mean_list = []
var_list = []
d_list = []

In [58]:
for value in range(10000):
    sample = np.random.choice(randomly_generated_x, size=10)
    mean_list.append(sample.mean())
    variance = sample.std()/ (10 ** .5)
    var_list.append(variance)
    d_list.append(variance/sample.mean())

In [59]:
print('D Standard Deviation: ' + str(statistics.stdev(d_list)))

D Standard Deviation: 0.04905431432898977


#### Part C

In [60]:
c_mean = 3
c_std = math.sqrt(3.24)

In [61]:
c_std

1.8

In [62]:
c_normal_randomly_generated = np.random.normal(loc=c_mean, scale=c_std, size=100)

In [63]:
mean_list = []
var_list = []
d_list = []

In [64]:
for value in range(10000):
    sample = np.random.choice(c_normal_randomly_generated, size=10)
    mean_list.append(sample.mean())
    variance = sample.std()/ (10 ** .5)
    var_list.append(variance)
    d_list.append(variance/sample.mean())

In [65]:
print('D Standard Deviation: ' + str(statistics.stdev(d_list)))

D Standard Deviation: 0.041459127038493235
